### ISSUE TITLE
Zistiť možnosti čítania občianskeho preukazu s čipom

### ISSUE THREAD

**Issue by KelloTomas** [BcHlavatyDaniel/Bc_Daniel_Hlavaty_sklad_net#1]
Používa sa to cez aplikáciu v PC, ktorá beží na pozadí. Treba skúsiť zistiť či ponúka možnosť prečítať meno a priezvisko cez nu.

https://portal.minv.sk/wps/wcm/connect/sk/site/main/obciansky-preukaz-s-cipom

https://www.slovensko.sk/sk/obciansky-preukaz-s-cipom/_obciansky-preukaz-s-cipom1

**Comment by HlavatyDaniel** [comment]
Napriek tomu ze tento sposob by bol funkcny, obcianske preukazy s cipom este nie su standardom, co znamena ze tymto sposobom nemozem registrovat vsetkych zakaznikov, co je nevyhovujuce. (citacku uz mam, este si to aj vyskusam a pridam kod ako sa to robi).
Dalsou moznostou je vyuzit strbinovu citacku, ktorej cena je vsak pre nas system nevyhovujuca.

**Comment by KelloTomas** [comment]
Pokial viem, obcianske s cipom uz standardom su. Akurat nie vsetci ich zatial maju. Ak dobre rozumiem. Obciansky s cipom budes zvladat precitat?

Tu strbinovu som zabudol zavolat. Budem volat tento tyzden stredu/stvrtok.

Ked vlozis kod s citanim obcianskeho, uzavri tuto ulohu
