### ISSUE TITLE
Tlac fakturu

### ISSUE THREAD

**Issue by KelloTomas** [BcHlavatyDaniel/Bc_Daniel_Hlavaty_sklad_net#11]
https://studuniza-my.sharepoint.com/:w:/g/personal/tomas_kello_fri_uniza_sk/ES8sgagNV6dHrdPzkjjJSSkBu7nm7enZyAmGOWNxGqsjcg?e=4L4VLO

asi to budes musiet exportovat do html, tovar vpisat do riadkov tabulky a najst moznosti tlace

**Comment by HlavatyDaniel** [comment]
Malo by to ficat, skusil som to na tlaciarni tu. Este nie je otestovane na virt. tlaciarni
