### ISSUE TITLE
Zistiť možnosti čítania identifikačných informácii z fotografie

### ISSUE THREAD

**Issue by KelloTomas** [BcHlavatyDaniel/Bc_Daniel_Hlavaty_sklad_net#2]
Zistiť možnosť prečítania údajov z občianskeho preukazu alebo pasu z naskenovaných dokumentov.

Pozícia mena, priezviska je presne daná. Takže sa dá vystrihnúť fotka a použiť dáke API na rozpoznávanie textu

**Comment by HlavatyDaniel** [comment]
Kniznica c# OCR, prve testy uz su v kode. Tento system by mohol fungovat, aj ked momentalne citanie funguje "nespolahlivo" (napriek rovnakemu umiestneniu,  niekedy text precita spravne niekedy nie)

**Comment by KelloTomas** [comment]
Na detajly sa mozeme pozriet spolu. Ak vie aspon nieco precitat. Je to super ;)

**Comment by KelloTomas** [comment]
nespolahlive. moxes o tom napisat v bakalarke ale neimplementovat
