### ISSUE TITLE
NuGet pre WPF aplikaciu

### ISSUE THREAD

**Issue by KelloTomas** [BcHlavatyDaniel/Bc_Daniel_Hlavaty_sklad_net#3]
NuGet balicek vo WPF aplikacii
-MaterialDesignThemes
-log4net - zapis logov co aplikacia robi
-MySql.Data

potom na ten dizajn si budes musiet nainstalovat trial DevExpress (platené GUI prvky v aplikacii)

**Comment by HlavatyDaniel** [comment]
installed. V priebehu tohto tyzdna sa pohrabem v design temach, + pridam logy
