### ISSUE TITLE
2 april

### ISSUE THREAD

**Issue by KelloTomas** [BcHlavatyDaniel/Bc_Daniel_Hlavaty_sklad_net#6]
podla priority
1. tovar - velkost ako TEXT. (S, M, L, ....)
2. Zoznam tovaru
3. modalne okno na pridavanie uziv. a tovar
4. hamburger menu
5. Zoznam uziv. pridat stlpec pocet tovarov naa sklade
6. filtrovanie podla vsetkych stlpcov

+ WEB App
Zoznam tovaru nasklade, filter nazov a velkost
+ moze byt zoznam tovaru vsetkych stavov pri vypisani tel cisla a priezviska

**Comment by HlavatyDaniel** [comment]
Zoznam tovaru -> done, ma sa dat aj niekam zneho prekliknut?
modalne okno na upravu uzivatelskeho tovaru, ups. teraz pozeram :D rano prehodim aj to
hamburger menu  -> done
filtrovanie podla vsetkych stlpcov -> done
Zoznam uziv. podla poctu tovaru rano pridam to mi uslo

**Comment by HlavatyDaniel** [comment]
Zoznam uziv podla poctu -> added
modalne okno na pridavanie uziv. tovaru added, modal okno na upravu existujuceho tovaru moved do obycajneho okna.
Teraz pracujem na -> description tovaru ako editable row detail.

**Comment by HlavatyDaniel** [comment]
Description tovaru ako editable row detail -> done aj do databazy,
Pridam to aj k oknu tabulke tovaru na sklade.
TO DO : Upracem kod kapanek, nastylujem tie (minimalne) buttony, velkost ako TEXT

**Comment by HlavatyDaniel** [comment]
pridane aj k tabulke tovaru na sklade.
Nastylovane celkom. Zajtra ..dneska ti volam po obede ako tie logy.
Objavil sa mi bug, ze v jednej tabulke sa mi otvara rowdetail na mouseclick na druhej nie. Je tam potom bug ze ked sa to otvori nie buttonom, tak sa nenacita description -.-. Rano fixnem

**Comment by HlavatyDaniel** [comment]
Nevermind, fixed.

**Comment by HlavatyDaniel** [comment]
TO DO - column combobox binding mam na ..zle, fixujem

**Comment by HlavatyDaniel** [comment]
fixed, davnejsie len som neokomentoval
