### ISSUE TITLE
tabulka zmien

### ISSUE THREAD

**Issue by KelloTomas** [BcHlavatyDaniel/Bc_Daniel_Hlavaty_sklad_net#7]
Tabulka kde bude
- id
- prepojenue na tovar
- cas zmeny
- typ ako int - zman ceny[1]/zmena stavu[2]
- text zmeny

Budu sa tam zaznamenavat zmeny ceny a zmeny stavu tovaru

**Comment by HlavatyDaniel** [comment]
Pridane
