### ISSUE TITLE
Pridat poznamku k tovaru

### ISSUE THREAD

**Issue by KelloTomas** [BcHlavatyDaniel/Bc_Daniel_Hlavaty_sklad_net#8]
Poznamka je len pre admina k tovaru. Nebnude na internete. Nieco v systeme. Servis biku,lyzi ci ine fakturovanie

**Comment by KelloTomas** [comment]
Skus spravit ten zoznam takto
![image](https://user-images.githubusercontent.com/8642127/55673365-9428df00-58a7-11e9-915d-bca535daa3b8.png)


V stlpci Akcia su tlacitka. U Upravit by som dal modalne okno s moznostou upravit vsetky data a tiez s LOGom o zmenach. Ak zmenis cenu tak sa vytvori aj novy log

**Comment by HlavatyDaniel** [comment]
jo, mal som nieco rozrebene ale kus inak, totok je jednoznacne better tak upravim a zajtra commitnem

**Comment by KelloTomas** [comment]
Robis to zlozito (sam by som to nezvladal s tym rozklikavanim ako to mas ty) a vo vysledku je to horsie. To meno asi zmen na Popis. a len jednoducho sa to snaz spravit

**Comment by HlavatyDaniel** [comment]
Alright, toto mam done, aj z databazou si rozumeju. Mam tam este kupu rozmlateneho kodu stymi logmi, do rana commitnem.

**Comment by HlavatyDaniel** [comment]
Toto menu pridane, description funguje upravitelne cez rowdetails.

**Comment by HlavatyDaniel** [comment]
it works tho. :D
Zajtra si v skole? na taku pol hodku by som ta rad prisiel navstivit, mam
nejake otazocky ktore by som ti najradsej na pc ukazal, ze ked toto tak co
sa ma stat. Diki.

ne 7. 4. 2019 o 10:17 Tomas Kello <notifications@github.com> napísal(a):
